<?php $v->layout('layout', ['title' => 'User Profile']) ?>

<h1>User Profile</h1>
<p>Hello, <?=$v($name)?></p>


<!-- Begin page content -->
<main role="main" class="container">
    <h1 class="mt-5">Главная страница</h1>
    <p class="lead">Для чтения заявко пройдите по сылки "Чтения заявок"</p>
    <p class="lead">Для отображения результата необходимо перейти в директорию или перейти по ссылки "Отобразить результат"</p>
    <p>Back to <a href="../sticky-footer/">the default sticky footer</a> minus the navbar.</p>
</main>