<?php $v->layout('layout', ['title' => 'User Profile']) ?>

<!-- Begin page content -->
<main role="main" class="container">
    <h1 class="mt-5">Главная страница</h1>
    <p>Проект, <?=$v($name)?></p>
    <p class="lead">Для чтения заявко пройдите по сылки "Чтения заявок"</p>
    <p class="lead">Для отображения результата необходимо перейти в директорию или перейти по ссылки "Отобразить результат"</p>
</main>